spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
  mail:
    host: ${SPRING_MAIL_HOST:mailhog}
    port: ${SPRING_MAIL_PORT:1025}
ntfy:
  url: ${NTFY_URL:http://ntfy:80}
