server:
  port: 8082

spring:
  application:
    name: attendance-service
  datasource:
    url: jdbc:postgresql://localhost:5432/smart_attendance
    username: sa_admin
    password: localdev123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  flyway:
    enabled: false
  data:
    redis:
      host: localhost
      port: 6379
      password: localdev123
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  threads:
    virtual:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
      show-components: always
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  level:
    com.hdbank.attendance: DEBUG
